content:
  - name: modular
    label: Modular Pages
    type: collection
    path: src
    format: raw
    filename: "{slug}.webc"
    subfolders: false
    fields:
      - name: slug
        label: Slug
        type: string
  - name: videos
    label: Videos
    type: collection
    path: src/_data/videos
    format: yaml
    filename: "{slug}.yml"
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: url
        label: URL
        type: string
      - name: date
        label: Date Uploaded
        type: date