content:
  - name: videos
    label: Videos
    type: collection
    path: src/_data/videos
    format: yaml
    filename: "{title}.yml"
    fields:
      - name: title
        label: Title
        type: string