content:
  - name: modular
    label: Modular Pages
    type: collection
    path: src
    format: yaml-frontmatter
    filename: "{primary}.webc"
    subfolders: false
    fields:
      - name: slug
        label: Slug
        type: string
    view:
      primary: slug
  - name: videos
    label: Videos
    type: collection
    path: src/_data/videos
    format: yaml
    filename: "{primary}.yml"
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: url
        label: URL
        type: string
      - name: date
        label: Date Uploaded
        type: date
    view:
      primary: slug