content:
  - name: modular
    label: Modular Pages
    type: collection
    path: src
    format: yaml-frontmatter
    filename: "{primary}.webc"
    subfolders: false
    fields:
      - name: slug
        label: Slug
        type: string
      - name: blocks
        label: Blocks
        type: block
        list: true
        blocks:
          - name: hero
            label: Hero
            component: hero
    view:
      primary: slug
  - name: videos
    label: Videos
    type: collection
    path: src/_data/videos
    format: yaml
    filename: "{primary}.yml"
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: url
        label: URL
        type: string
      - name: date
        label: Date Uploaded
        type: date
    view:
      primary: slug
components:
  hero:
    label: Hero
    type: object
    fields:
      - name: video
        label: Video
        type: reference
        options:
          search: title
          label: title
          collection: videos